-- MySQL Script generated by MySQL Workbench
-- Mon May  6 01:04:05 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sportgymdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sportgymdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sportgymdb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `sportgymdb` ;

-- -----------------------------------------------------
-- Table `sportgymdb`.`suscripcion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportgymdb`.`suscripcion` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `cantidad` INT NULL DEFAULT NULL,
  `disponibilidad` VARCHAR(255) NULL DEFAULT NULL,
  `duracion` VARCHAR(255) NULL DEFAULT NULL,
  `precio` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sportgymdb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportgymdb`.`usuarios` (
  `id_usuario` BIGINT NOT NULL AUTO_INCREMENT,
  `direccion` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `nombres` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `telefono` BIGINT NULL DEFAULT NULL,
  `suscripcion_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `UKkfsp0s1tflm1cwlj8idhqsad0` (`email` ASC) VISIBLE,
  INDEX `FK6an2hhwavepo13ato1tdxiopf` (`suscripcion_id` ASC) VISIBLE,
  CONSTRAINT `FK6an2hhwavepo13ato1tdxiopf`
    FOREIGN KEY (`suscripcion_id`)
    REFERENCES `sportgymdb`.`suscripcion` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sportgymdb`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportgymdb`.`productos` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `cantidad` INT NULL DEFAULT NULL,
  `imagen` VARCHAR(5000) NULL DEFAULT NULL,
  `nombre_producto` VARCHAR(255) NULL DEFAULT NULL,
  `precio` INT NULL DEFAULT NULL,
  `usuario_id_usuario` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK7vo2f29g03wwn81cfyllxkqax` (`usuario_id_usuario` ASC) VISIBLE,
  CONSTRAINT `FK7vo2f29g03wwn81cfyllxkqax`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `sportgymdb`.`usuarios` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sportgymdb`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportgymdb`.`roles` (
  `id_role` BIGINT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_role`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sportgymdb`.`usuarios_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportgymdb`.`usuarios_roles` (
  `id_usuario` BIGINT NOT NULL,
  `id_role` BIGINT NOT NULL,
  INDEX `FK33v8y5al18q1g8v661ewo6wla` (`id_role` ASC) VISIBLE,
  INDEX `FKt5th9sao5wjukq9ij7154ktuw` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `FK33v8y5al18q1g8v661ewo6wla`
    FOREIGN KEY (`id_role`)
    REFERENCES `sportgymdb`.`roles` (`id_role`),
  CONSTRAINT `FKt5th9sao5wjukq9ij7154ktuw`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `sportgymdb`.`usuarios` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
